/* PROCEDURES */

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONES(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL','COM','RES')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONES ADD CONSTRAINT FK_PESSOA_TELEFONE
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M','21-08-2001')
INSERT INTO PESSOA VALUES('DANIEL','M','12-09-2003')
INSERT INTO PESSOA VALUES('MARCELO','M','25-12-1987')

INSERT INTO TELEFONES VALUES('CEL','43289',1)
INSERT INTO TELEFONES VALUES('COM','4353489',1)
INSERT INTO TELEFONES VALUES('CEL','4853249',2)
INSERT INTO TELEFONES VALUES('CEL','434729',2)
INSERT INTO TELEFONES VALUES('COM','43219',3)
INSERT INTO TELEFONES VALUES('COM','3287',2)
INSERT INTO TELEFONES VALUES('CEL','43287',3)
GO


/* CRIANDO UMA PROCEDURE */

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

/* EXECUÇÃO DA PROCEDURES */

EXEC SOMA
GO

/* PROCEDURES COM PARÂMETROS */

CREATE PROC CONTA @NUMERO1 INT, @NUMERO2 INT
AS
	SELECT @NUMERO1 + @NUMERO2
GO

EXEC CONTA 90, 78
GO

/* APAGANDO PROCEDURE */

DROP PROC CONTA
GO

/* PROCEDURES EM TABELAS */

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONES
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

CREATE PROC PROC_TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONES
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

EXEC PROC_TELEFONES 'CEL'
GO

/* PARÂMETROS DE OUTPUT */

SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONES
GROUP BY TIPO
GO

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/* EXECUÇÃO DA PROC COM PARAMETRO DE SAIDA */

DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO


/* PROCEDURE DE CADASTRO */

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE, @TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO)

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY) -- GUARDA O ÚLTIMO IDENTITY INSERIDO NA SECAO

	INSERT INTO TELEFONES VALUES(@TIPO, @NUMERO, @FK)
GO

EXEC CADASTRO 'JORGE', 'M', '08/03/2003', 'CEL', '947538'
GO

SELECT * FROM PESSOA
INNER JOIN TELEFONES
ON IDPESSOA = ID_PESSOA
GO