/* função de agregação */

/* querry simples */

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRÊNCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACAO;

/* AGRUPANDO POR SEXO COM GROUP BY */

SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NÚMERO DE FUNCIONÁRIOS DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MÁXIMO DE SALÁRIOS */

SELECT MAX(SALARIO) AS "MAIOR SALÁRIO" FROM FUNCIONARIOS;

/* EXIBINDO O MÍNIMO DE SALÁRIOS */

SELECT MIN(SALARIO) AS "MENOR SALÁRIO" FROM FUNCIONARIOS;

/* EXIBINDO O MÍNIMO E O MÁXIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MIN(SALARIO) AS "MENOR SALARIO", MAX(SALARIO) AS "MAIOR SALARIO" FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;
