/* função de agregação */

/* querry simples */

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRÊNCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACAO;

/* AGRUPANDO POR SEXO COM GROUP BY */

SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NÚMERO DE FUNCIONÁRIOS DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MÁXIMO DE SALÁRIOS */

SELECT MAX(SALARIO) AS "MAIOR SALÁRIO" FROM FUNCIONARIOS;

/* EXIBINDO O MÍNIMO DE SALÁRIOS */

SELECT MIN(SALARIO) AS "MENOR SALÁRIO" FROM FUNCIONARIOS;

/* EXIBINDO O MÍNIMO E O MÁXIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MIN(SALARIO) AS "MENOR SALARIO", MAX(SALARIO) AS "MAIOR SALARIO" FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;


/* estatísticas */

/* mostrando uma quantidade limitada de linhas */

SELECT * FROM FUNCIONARIOS LIMIT 10;

/* QUAL O GASTO TOTAL DE SALÁRIO GASTO PELA EMPRESA */

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

/* QUAL O MONTANTE TOTAL QUE CADA DEPARTAMENTO RECEBE */

SELECT DEPARTAMENTO, SUM(SALARIO) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* POR DEPARTAMENTO QUAL O TOTAL E A MÉDIA PAGA PARA OS FUNCIONARIOS */

SELECT DEPARTAMENTO, SUM(SALARIO), AVG(SALARIO) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* ORDENANDO */

SELECT DEPARTAMENTO, SUM(SALARIO), AVG(SALARIO) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3;


/* IMPORTANDO CSV */

CREATE TABLE MAQUINAS(
    MAQUINAS VARCHAR(20),
    DIA INT,
    QTD NUMERIC(10,2)
);

COPY MAQUINAS FROM 'C:\Users\Gabriel\Downloads\\LogMaquinas.csv' 
DELIMITER ','
CSV HEADER;

/* QUAL A MEDIA DE CADA MAQUINA */

SELECT MAQUINAS, AVG(QTD) FROM MAQUINAS
GROUP BY MAQUINAS;

/* ARREDONDANDO */

SELECT MAQUINAS, ROUND(AVG(QTD),2) FROM MAQUINAS
GROUP BY MAQUINAS
ORDER BY 2 DESC;


/* QUAL A MODA DE TODAS AS QUANTIDADES */

SELECT MAQUINAS, QTD, COUNT(*) FROM MAQUINAS
GROUP BY MAQUINAS, QTD
ORDER BY 3 DESC;

/* MODA DE  CADA MAQUINA */

SELECT MAQUINAS, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINAS = 'Maquina 01'
GROUP BY MAQUINAS, QTD
ORDER BY 3 DESC;

/* MODA DO DATASET INTEIRO */

SELECT QTD, COUNT(*) FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* QUAL O MÁXIMO, MÍNIMO E AMPLITUDE DE CADA MAQUINA */

SELECT MAQUINAS, MAX(QTD) AS MAXIMO, MIN(QTD) AS MINIMO, MAX(QTD) - MIN(QTD) AS AMPLITUDE FROM MAQUINAS
GROUP BY MAQUINAS
ORDER BY 4 DESC;

/* DESVIO PADRAO E VARIANCIA */

SELECT MAQUINAS, STDDEV_POP(QTD) AS "DESVIO PADRAO", VAR_POP(QTD) AS "VARIANCIA"
FROM MAQUINAS
GROUP BY MAQUINAS
ORDER BY 2;


/* CRIANDO FUNÇÃO PARA MEDIANA */

CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
    RETURNS NUMERIC AS
$$
    SELECT AVG(val)
    FROM (
        SELECT val
        FROM unnest ($1) val
        ORDER BY 1
        LIMIT 2 - MOD(array_upper($1, 1), 2)
        OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
    ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE median(numeric) (
  SFUNC=array_append,
  STYPE=numeric[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);

/* ENCONTRANDO A MEDIANA */

SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINAS = 'Maquina 01';

/* MAIS ALGUNS INSERT */

INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);