/* PROJETO_EXERCICIO */

CREATE DATABASE PROJETO_EXERCICIO;
USE PROJETO_EXERCICIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE CORES(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);


CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
);


/* CONSTRAINTS */

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES CORES(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PARA INSERIR NESSE CASO É PRECISO CRIAR ALGUNS VALORES ANTES
COMO COR, MARCA PARA O CARRO */
/* TELEFONE CASO O CLIENTE TENHA, PORÉM O CLIENTE TEM DE SER CADASTRADO ANTES DO TELEFONE */

DELIMITER $

CREATE PROCEDURE CADASTRO_CARRO(C_MODELO VARCHAR(30), C_PLACA VARCHAR(30), C_MARCA INT)
BEGIN
	INSERT INTO CARRO VALUES(NULL, C_MODELO, C_PLACA, C_MARCA);
END 
$

CREATE PROCEDURE CADASTRO_MARCA(C_MARCA VARCHAR(30))
BEGIN
	INSERT INTO MARCA VALUES(NULL,C_MARCA);
END 
$

CALL CADASTRO_MARCA('RENAULT');
CALL CADASTRO_CARRO('CAPTUR', 'FAKJF321', 1);

CREATE PROCEDURE CADASTRO_CORES(C_COR VARCHAR(30))
BEGIN
	INSERT INTO CORES VALUES(NULL, C_COR);
END
$

CREATE PROCEDURE CADASTRO_CARRO_COR(C_ID_CARRO INT, C_ID_COR INT)
BEGIN
	INSERT INTO CARRO_COR VALUES(C_ID_CARRO, C_ID_COR);
END
$

CREATE PROCEDURE CADASTRO_TELEFONE(C_TIPO ENUM('CEL', 'RES', 'COM'),C_NUMERO VARCHAR(30), C_ID_CLIENTE INT)
BEGIN
	INSERT INTO TELEFONE VALUES(NULL,C_TIPO,C_NUMERO,C_ID_CLIENTE);
END
$

CREATE PROCEDURE CADASTRO_CLIENTE(C_NOME VARCHAR(30), C_SEXO ENUM('M','F'), C_ID_CARRO INT)
BEGIN
	INSERT INTO CLIENTE VALUES(NULL, C_NOME, C_SEXO, C_ID_CARRO);
END
$

DELIMITER ;

CALL CADASTRO_CORES('PRETO');
CALL CADASTRO_CORES('AZUL');

CALL CADASTRO_CARRO_COR(1,1);

CALL CADASTRO_CLIENTE('PEDRO','M',1);

CALL CADASTRO_TELEFONE('CEL', '545325443',1);
CALL CADASTRO_TELEFONE('RES', '65487289', 1);