CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(100),
	NOME_AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	NOME_EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78.99,'RJ',2018);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150.98,'RJ',2019);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78.98,'ES',2011);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS',2018);

INSERT INTO LIVROS (NOME_LIVRO,NOME_AUTOR,SEXO,PAGINAS,NOME_EDITORA,VALOR,UF,ANO) VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56.58,'SP',2017);

/* TRAZENDO TODOS OS DADOS */
SELECT * FROM LIVROS;

/* TRAZENDO NOME DO LIVRO E DA EDITORA */
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/* TRAZENDO O NOME DO LIVRO E O UF COM AUTOR MASCULINO */
SELECT NOME_LIVRO, UF FROM LIVROS
WHERE SEXO ='M';

/* TRAZENDO NOME DO LIVRO E PÁGINAS DO SEXO FEMININO */
SELECT NOME_LIVRO, PAGINAS FROM LIVROS
WHERE SEXO ='F';

/* TRAZENDO  VALOR ONDE UF É SP */
SELECT VALOR FROM LIVROS
WHERE UF ='SP'

/* TRAZENDO NOME DO LIVRO E DO AUTOR, ONDE SEXO É MASCULINO E UF SP OU RJ, NESSE CASO DO RJ IRÁ VIR AS MULHERES */
SELECT NOME_LIVRO, NOME_AUTOR FROM LIVROS
WHERE SEXO='M' AND UF='SP' OR UF='RJ';