Secao_13

/* DELIMITADOR */

/* ALTERANDO O DELIMITADOR PARA QUALQUER OUTRO CARACTER, CASO O BANCO SEJA FECHADO O BANCO VOLTA AO DELIMITADOR PADRÃO */

DELIMITER $


/* STORAGE PROCEDURES */

/* PRIMEIRO MUDA O DELIMITADOR E DEPOIS MONTA CONFORME A ESTRUTURA */
DELIMITER $

CREATE PROCEDURE NOME()
BEGIN
	
	QUALQUER PROGRAMAÇÃO;

END
$


CREATE PROCEDURE NOME_EMPRESA()
BEGIN
	
	SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;

END
$

/* CHAMANDO UMA PROCEDURE */

CALL NOME_EMPRESA()$

DELIMITER ;

CALL NOME_EMPRESA();

/* PROCEDURES COM PARAMETROS */

CREATE PROCEDURE CONTA()
BEGIN

	SELECT 10 + 10 AS CONTA;

END
$

/* APAGANDO UMA PROCEDURE */

DROP PROCEDURE CONTA$


CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN

	SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100,50)$

DROP DATABASE COMERCIO;
DROP DATABASE EXERCICIO;
DROP DATABASE LIVRARIA;
DROP DATABASE PROJETO;


/* PROCEDURES */

CREATE DATABASE PROJETO;
USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, 'JAVA',30,500.000);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BANCO DE DADOS',40,700.000);

SELECT * FROM CURSOS;

DELIMITER #

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
							P_HORAS INT(3),
							P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL,P_NOME, P_HORAS, P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER',35, 3000.00);
CALL CAD_CURSO('POWER BI',20, 1000.00);
CALL CAD_CURSO('TABLEAU',30, 1200.00);

CREATE PROCEDURE VIEW()
BEGIN
	SELECT * FROM CURSOS;
END
#

DELIMITER ;
CALL VIEW();


/* FUNÇÕES MAX, MIN, AVG, TRUNCATE, SUM SÃO SIMPLES E DIRETAS NÃO PRECISA ESCREVER AQUI */



