USE PROJETO;

/* PRIMEIRA FORMA NORMAL */

/* 
1 - TODO CAMPO  VETORIZADO SE TORNARÁ OUTRA TABELA

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA
QUANDO O CAMPO FOR DIVISÍVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO.
ISSO RECEBE O NOME DE CHAVE PRIMÁRIA OU PRIMARY KEY;
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)	
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

/* ENDERECO OBRIGATÓRIO
CADASTRO DE SOMENTE UM

TELEFONE -  NAO OBRIGATORIO
PODE CADASTRAR MAIS DE 1 */

/* CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA  QUE VAI ATÉ A OUTRA OUTRA TABELA PARA FAZER REFERÊNCIA ENTRE REGISTROS */

/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A  CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE N */

INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M','JOAO@IVI.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS', 'M','CARLOS@IVI.COM','478926358');
INSERT INTO CLIENTE VALUES(NULL, 'ANA', 'F','ANA@IVI.COM','58974635');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA', 'F',NULL,'467832154');
INSERT INTO CLIENTE VALUES(NULL, 'JORGE', 'M','JORGE@IVI.COM','46783215423');
INSERT INTO CLIENTE VALUES(NULL, 'CELIA', 'F','CELIA@IVI.COM','5756482634');

+-----------+--------+------+----------------+-------------+
| IDCLIENTE | NOME   | SEXO | EMAIL          | CPF         |
+-----------+--------+------+----------------+-------------+
|         1 | JOAO   | M    | JOAO@IVI.COM   | 76567587887 |
|         2 | CARLOS | M    | CARLOS@IVI.COM | 478926358   |
|         3 | ANA    | F    | ANA@IVI.COM    | 58974635    |
|         4 | CLARA  | F    | NULL           | 467832154   |
|         5 | JORGE  | M    | JORGE@IVI.COM  | 46783215423 |
|         6 | CELIA  | F    | CELIA@IVI.COM  | 5756482634  |
+-----------+--------+------+----------------+-------------+

DESC ENDERECO;

INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTONIO SA','CENTRO','BELO HORIZONTE','MG', 4);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ', 1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRES VARGAS','JARDINS','SAO PAULO','SP', 3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ', 2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA URUGUAIANA','CENTRO','VITORIA','ES', 5);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ', 6);

DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL,'CEL','76543243',5);

INSERT INTO TELEFONE VALUES(NULL,'RES','76543243',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','58674325',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','59847653',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','43267548',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','6745783',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','46723782',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','4823645',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','5234652',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','4632198',2);