/* FILTRANDO VALORES NULOS */

SHOW DATABASES;
USE PROJETO;
SHOW TABLES;
SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

/* USANDO UPTADE PARA ATT VALORES JÁ INSERIDOS */

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM';
SELECT NOME, EMAIL FROM CLIENTE;

/* FILTRANDO ESPECÍFICO PARA NÃO MUDAR TODOS */

UPDATE CLIENTE SET EMAIL = 'JOAOA@IG.COM.BR' WHERE NOME = 'JOAO';
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'JORGE@IG.COM.BR' WHERE NOME = 'JORGE';
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'CELIA@IG.COM.BR' WHERE NOME = 'CELIA';
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'ANA@IG.COM.BR' WHERE NOME = 'ANA';
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'CARLA@IG.COM.BR' WHERE NOME = 'CARLA';
SELECT NOME, EMAIL FROM CLIENTE;


/* DELETANDO REGISTOS COM DELETE */

SELECT COUNT(*) FROM CLIENTE; -- TOTAL 6

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'ANA'; -- TOTAL 1

DELETE FROM CLIENTE WHERE NOME = 'ANA';

INSERT INTO CLIENTE VALUES('CARLA','F','C.LOPES@UOL.COM',45338854,'4575-0048', 'RUACOPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@IG.COM.BR';
DELETE FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@IG.COM.BR';